### ISSUE TITLE
No hammertools submenu in the Applications/Shift+F10 context menu under Chrome

### ISSUE THREAD

**Issue by ns-studios** [ogomez92/hammertools#1]
Installed addon as suggested, made sure it was enabled, but the context menu doesn't have the hammertools submenu.
Using Chrome 87.0.4280.141 (Official Build) (64-bit) Under Windows 10 20h2.

**Comment by ogomez92** [comment]
Sorry, try now. Let me know if it works. Use the one inside the chrome folder.

**Comment by ns-studios** [comment]
Can confirm that I can see the hammertools menue with items in it, but haven't tried any of the features yet in practice.
Thank you so much for porting this to Chrome. I was so annoyed that the original was for FF only.

**Comment by ogomez92** [comment]
if you can see the menu, everything works. I have tested it.
