### ISSUE TITLE
Update extension to incorporate latest changes

### ISSUE THREAD

**Issue by tmthywynn8** [ogomez92/hammertools#2]
In June of this year, @jcsteh added the ability to kill aria-label and ARIA roles (see [this commit][1]). If it isn't too much work, it would be appreciated if this can be incorporated into the Chromium extension as well.

[1]: https://github.com/jcsteh/axSHammer/commit/c523f6d453f49b6b52c1d04752060915359c4eb9

**Comment by ogomez92** [comment]
Hello @tmthywynn8 
I have made the following changes:


- Updated manifest to version 3
- added kill ARIA labels and roles
- Refactor code for Chrome
The mac version... I'm considering removing it and just letting mac users use the Chrome version, any thoughts?

I tried to modify it a bit but can't test atm.

I'm closing this issue, please do test as there's been a lot of refactoring (I tested what I could).
If you have any more ideas of things we can add to this, let me know.



Thanks.

**Comment by tmthywynn8** [comment]
I don't think killing aria-label is working as expected. Steps to reproduce:

1. Go to the address and search bar.
2. Paste the following and press *Enter*: ```data:text/html,<button aria-label="label">name</button>```
3. Press *Applications* or *Shift+F10* and choose Hammertools Menu➡Kill all aria-label.
  * Expected: the button should be labeled "name".
  * Actual: The button is labeled "label".

**Comment by tmthywynn8** [comment]
Oops. Please disregard as I can't get it to work in Firefox either. I need to come up with a better test.

**Comment by tmthywynn8** [comment]
Okay, I think I got it to work:

1. Create an HTML file with the following contents:
```html
<html>
  <head>
    <title>test</title>
  </head>
  <body>
    <p>
      <button aria-label="label">name</button>
    </p>
  </body>
</html>
```
2. Open in it in a Chromium browser.
3. Press Applications or Shift+F10 and choose Hammertools Menu➡Kill all aria-label.
  * Expected: the button should be labeled "name".
  * Actual: The button is labeled "label".
